# agendamento com o cron
# Editar o crontab com: crontab -e
# Minuto Hora Dia-do-Mes Mes Dia-da-semana Comando

# Atualiza o sistema todo o dia as 4h da manha
0 4 * * * /caminho/para/update.sh >> /var/log/update.log 2>&1

# Faz backup todo domingo as 23h
0 23 * * 0 /caminho/para/backup.sh >> /var/log/backup.log 2>&1

# Monitora o nginx a cada 15 minutos
*/15 * * * * /caminhop/para/monitor.sh >> /var/log/monitor.log 2>&1